// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/roddd/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// GetAWSProfile provides a mock function with given fields: bucket
func (_m *MockConfigProvider) GetAWSProfile(bucket string) string {
	ret := _m.Called(bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetAWSProfile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(bucket)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigProvider_GetAWSProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAWSProfile'
type MockConfigProvider_GetAWSProfile_Call struct {
	*mock.Call
}

// GetAWSProfile is a helper method to define mock.On call
//   - bucket string
func (_e *MockConfigProvider_Expecter) GetAWSProfile(bucket interface{}) *MockConfigProvider_GetAWSProfile_Call {
	return &MockConfigProvider_GetAWSProfile_Call{Call: _e.mock.On("GetAWSProfile", bucket)}
}

func (_c *MockConfigProvider_GetAWSProfile_Call) Run(run func(bucket string)) *MockConfigProvider_GetAWSProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigProvider_GetAWSProfile_Call) Return(_a0 string) *MockConfigProvider_GetAWSProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetAWSProfile_Call) RunAndReturn(run func(string) string) *MockConfigProvider_GetAWSProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvironment provides a mock function with given fields: name
func (_m *MockConfigProvider) GetEnvironment(name string) (types.EnvironmentConfig, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironment")
	}

	var r0 types.EnvironmentConfig
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (types.EnvironmentConfig, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) types.EnvironmentConfig); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(types.EnvironmentConfig)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockConfigProvider_GetEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvironment'
type MockConfigProvider_GetEnvironment_Call struct {
	*mock.Call
}

// GetEnvironment is a helper method to define mock.On call
//   - name string
func (_e *MockConfigProvider_Expecter) GetEnvironment(name interface{}) *MockConfigProvider_GetEnvironment_Call {
	return &MockConfigProvider_GetEnvironment_Call{Call: _e.mock.On("GetEnvironment", name)}
}

func (_c *MockConfigProvider_GetEnvironment_Call) Run(run func(name string)) *MockConfigProvider_GetEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigProvider_GetEnvironment_Call) Return(_a0 types.EnvironmentConfig, _a1 bool) *MockConfigProvider_GetEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigProvider_GetEnvironment_Call) RunAndReturn(run func(string) (types.EnvironmentConfig, bool)) *MockConfigProvider_GetEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// GetFallbackUtilityIDs provides a mock function with no fields
func (_m *MockConfigProvider) GetFallbackUtilityIDs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFallbackUtilityIDs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockConfigProvider_GetFallbackUtilityIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFallbackUtilityIDs'
type MockConfigProvider_GetFallbackUtilityIDs_Call struct {
	*mock.Call
}

// GetFallbackUtilityIDs is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetFallbackUtilityIDs() *MockConfigProvider_GetFallbackUtilityIDs_Call {
	return &MockConfigProvider_GetFallbackUtilityIDs_Call{Call: _e.mock.On("GetFallbackUtilityIDs")}
}

func (_c *MockConfigProvider_GetFallbackUtilityIDs_Call) Run(run func()) *MockConfigProvider_GetFallbackUtilityIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetFallbackUtilityIDs_Call) Return(_a0 []string) *MockConfigProvider_GetFallbackUtilityIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetFallbackUtilityIDs_Call) RunAndReturn(run func() []string) *MockConfigProvider_GetFallbackUtilityIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetKubectlContexts provides a mock function with given fields: env
func (_m *MockConfigProvider) GetKubectlContexts(env string) []string {
	ret := _m.Called(env)

	if len(ret) == 0 {
		panic("no return value specified for GetKubectlContexts")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockConfigProvider_GetKubectlContexts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKubectlContexts'
type MockConfigProvider_GetKubectlContexts_Call struct {
	*mock.Call
}

// GetKubectlContexts is a helper method to define mock.On call
//   - env string
func (_e *MockConfigProvider_Expecter) GetKubectlContexts(env interface{}) *MockConfigProvider_GetKubectlContexts_Call {
	return &MockConfigProvider_GetKubectlContexts_Call{Call: _e.mock.On("GetKubectlContexts", env)}
}

func (_c *MockConfigProvider_GetKubectlContexts_Call) Run(run func(env string)) *MockConfigProvider_GetKubectlContexts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigProvider_GetKubectlContexts_Call) Return(_a0 []string) *MockConfigProvider_GetKubectlContexts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetKubectlContexts_Call) RunAndReturn(run func(string) []string) *MockConfigProvider_GetKubectlContexts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
