// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: url
func (_m *MockHTTPClient) Get(url string) (io.ReadCloser, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.ReadCloser, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockHTTPClient_Expecter) Get(url interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(url string)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(_a0 io.ReadCloser, _a1 error) *MockHTTPClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(string) (io.ReadCloser, error)) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
