// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/zerogee00/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockK8sClient is an autogenerated mock type for the K8sClient type
type MockK8sClient struct {
	mock.Mock
}

type MockK8sClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK8sClient) EXPECT() *MockK8sClient_Expecter {
	return &MockK8sClient_Expecter{mock: &_m.Mock}
}

// GetUtilityClipIDs provides a mock function with given fields: config
func (_m *MockK8sClient) GetUtilityClipIDs(config types.EnvironmentConfig) ([]string, error) {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for GetUtilityClipIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.EnvironmentConfig) ([]string, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(types.EnvironmentConfig) []string); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(types.EnvironmentConfig) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockK8sClient_GetUtilityClipIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUtilityClipIDs'
type MockK8sClient_GetUtilityClipIDs_Call struct {
	*mock.Call
}

// GetUtilityClipIDs is a helper method to define mock.On call
//   - config types.EnvironmentConfig
func (_e *MockK8sClient_Expecter) GetUtilityClipIDs(config interface{}) *MockK8sClient_GetUtilityClipIDs_Call {
	return &MockK8sClient_GetUtilityClipIDs_Call{Call: _e.mock.On("GetUtilityClipIDs", config)}
}

func (_c *MockK8sClient_GetUtilityClipIDs_Call) Run(run func(config types.EnvironmentConfig)) *MockK8sClient_GetUtilityClipIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockK8sClient_GetUtilityClipIDs_Call) Return(_a0 []string, _a1 error) *MockK8sClient_GetUtilityClipIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockK8sClient_GetUtilityClipIDs_Call) RunAndReturn(run func(types.EnvironmentConfig) ([]string, error)) *MockK8sClient_GetUtilityClipIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetupContext provides a mock function with given fields: environment
func (_m *MockK8sClient) SetupContext(environment string) error {
	ret := _m.Called(environment)

	if len(ret) == 0 {
		panic("no return value specified for SetupContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(environment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockK8sClient_SetupContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupContext'
type MockK8sClient_SetupContext_Call struct {
	*mock.Call
}

// SetupContext is a helper method to define mock.On call
//   - environment string
func (_e *MockK8sClient_Expecter) SetupContext(environment interface{}) *MockK8sClient_SetupContext_Call {
	return &MockK8sClient_SetupContext_Call{Call: _e.mock.On("SetupContext", environment)}
}

func (_c *MockK8sClient_SetupContext_Call) Run(run func(environment string)) *MockK8sClient_SetupContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockK8sClient_SetupContext_Call) Return(_a0 error) *MockK8sClient_SetupContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockK8sClient_SetupContext_Call) RunAndReturn(run func(string) error) *MockK8sClient_SetupContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK8sClient creates a new instance of MockK8sClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK8sClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK8sClient {
	mock := &MockK8sClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
