// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/zerogee00/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockKMSClient is an autogenerated mock type for the KMSClient type
type MockKMSClient struct {
	mock.Mock
}

type MockKMSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMSClient) EXPECT() *MockKMSClient_Expecter {
	return &MockKMSClient_Expecter{mock: &_m.Mock}
}

// CheckKeyExists provides a mock function with given fields: keyID, config
func (_m *MockKMSClient) CheckKeyExists(keyID string, config types.EnvironmentConfig) (bool, map[string]interface{}, error) {
	ret := _m.Called(keyID, config)

	if len(ret) == 0 {
		panic("no return value specified for CheckKeyExists")
	}

	var r0 bool
	var r1 map[string]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) (bool, map[string]interface{}, error)); ok {
		return rf(keyID, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) bool); ok {
		r0 = rf(keyID, config)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) map[string]interface{}); ok {
		r1 = rf(keyID, config)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(string, types.EnvironmentConfig) error); ok {
		r2 = rf(keyID, config)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockKMSClient_CheckKeyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckKeyExists'
type MockKMSClient_CheckKeyExists_Call struct {
	*mock.Call
}

// CheckKeyExists is a helper method to define mock.On call
//   - keyID string
//   - config types.EnvironmentConfig
func (_e *MockKMSClient_Expecter) CheckKeyExists(keyID interface{}, config interface{}) *MockKMSClient_CheckKeyExists_Call {
	return &MockKMSClient_CheckKeyExists_Call{Call: _e.mock.On("CheckKeyExists", keyID, config)}
}

func (_c *MockKMSClient_CheckKeyExists_Call) Run(run func(keyID string, config types.EnvironmentConfig)) *MockKMSClient_CheckKeyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockKMSClient_CheckKeyExists_Call) Return(_a0 bool, _a1 map[string]interface{}, _a2 error) *MockKMSClient_CheckKeyExists_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockKMSClient_CheckKeyExists_Call) RunAndReturn(run func(string, types.EnvironmentConfig) (bool, map[string]interface{}, error)) *MockKMSClient_CheckKeyExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetDecryptionKey provides a mock function with given fields: keyID, config
func (_m *MockKMSClient) GetDecryptionKey(keyID string, config types.EnvironmentConfig) ([]byte, error) {
	ret := _m.Called(keyID, config)

	if len(ret) == 0 {
		panic("no return value specified for GetDecryptionKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) ([]byte, error)); ok {
		return rf(keyID, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) []byte); ok {
		r0 = rf(keyID, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) error); ok {
		r1 = rf(keyID, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKMSClient_GetDecryptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDecryptionKey'
type MockKMSClient_GetDecryptionKey_Call struct {
	*mock.Call
}

// GetDecryptionKey is a helper method to define mock.On call
//   - keyID string
//   - config types.EnvironmentConfig
func (_e *MockKMSClient_Expecter) GetDecryptionKey(keyID interface{}, config interface{}) *MockKMSClient_GetDecryptionKey_Call {
	return &MockKMSClient_GetDecryptionKey_Call{Call: _e.mock.On("GetDecryptionKey", keyID, config)}
}

func (_c *MockKMSClient_GetDecryptionKey_Call) Run(run func(keyID string, config types.EnvironmentConfig)) *MockKMSClient_GetDecryptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockKMSClient_GetDecryptionKey_Call) Return(_a0 []byte, _a1 error) *MockKMSClient_GetDecryptionKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKMSClient_GetDecryptionKey_Call) RunAndReturn(run func(string, types.EnvironmentConfig) ([]byte, error)) *MockKMSClient_GetDecryptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKMSClient creates a new instance of MockKMSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMSClient {
	mock := &MockKMSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
