// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/zerogee00/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockManifestAnalyzer is an autogenerated mock type for the ManifestAnalyzer type
type MockManifestAnalyzer struct {
	mock.Mock
}

type MockManifestAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifestAnalyzer) EXPECT() *MockManifestAnalyzer_Expecter {
	return &MockManifestAnalyzer_Expecter{mock: &_m.Mock}
}

// AnalyzeDASH provides a mock function with given fields: path, config
func (_m *MockManifestAnalyzer) AnalyzeDASH(path string, config types.EnvironmentConfig) (*types.MediaAnalysis, error) {
	ret := _m.Called(path, config)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeDASH")
	}

	var r0 *types.MediaAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) (*types.MediaAnalysis, error)); ok {
		return rf(path, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) *types.MediaAnalysis); ok {
		r0 = rf(path, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MediaAnalysis)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) error); ok {
		r1 = rf(path, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManifestAnalyzer_AnalyzeDASH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeDASH'
type MockManifestAnalyzer_AnalyzeDASH_Call struct {
	*mock.Call
}

// AnalyzeDASH is a helper method to define mock.On call
//   - path string
//   - config types.EnvironmentConfig
func (_e *MockManifestAnalyzer_Expecter) AnalyzeDASH(path interface{}, config interface{}) *MockManifestAnalyzer_AnalyzeDASH_Call {
	return &MockManifestAnalyzer_AnalyzeDASH_Call{Call: _e.mock.On("AnalyzeDASH", path, config)}
}

func (_c *MockManifestAnalyzer_AnalyzeDASH_Call) Run(run func(path string, config types.EnvironmentConfig)) *MockManifestAnalyzer_AnalyzeDASH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockManifestAnalyzer_AnalyzeDASH_Call) Return(_a0 *types.MediaAnalysis, _a1 error) *MockManifestAnalyzer_AnalyzeDASH_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManifestAnalyzer_AnalyzeDASH_Call) RunAndReturn(run func(string, types.EnvironmentConfig) (*types.MediaAnalysis, error)) *MockManifestAnalyzer_AnalyzeDASH_Call {
	_c.Call.Return(run)
	return _c
}

// AnalyzeHLS provides a mock function with given fields: path, config
func (_m *MockManifestAnalyzer) AnalyzeHLS(path string, config types.EnvironmentConfig) (*types.MediaAnalysis, error) {
	ret := _m.Called(path, config)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeHLS")
	}

	var r0 *types.MediaAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) (*types.MediaAnalysis, error)); ok {
		return rf(path, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) *types.MediaAnalysis); ok {
		r0 = rf(path, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MediaAnalysis)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) error); ok {
		r1 = rf(path, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManifestAnalyzer_AnalyzeHLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeHLS'
type MockManifestAnalyzer_AnalyzeHLS_Call struct {
	*mock.Call
}

// AnalyzeHLS is a helper method to define mock.On call
//   - path string
//   - config types.EnvironmentConfig
func (_e *MockManifestAnalyzer_Expecter) AnalyzeHLS(path interface{}, config interface{}) *MockManifestAnalyzer_AnalyzeHLS_Call {
	return &MockManifestAnalyzer_AnalyzeHLS_Call{Call: _e.mock.On("AnalyzeHLS", path, config)}
}

func (_c *MockManifestAnalyzer_AnalyzeHLS_Call) Run(run func(path string, config types.EnvironmentConfig)) *MockManifestAnalyzer_AnalyzeHLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockManifestAnalyzer_AnalyzeHLS_Call) Return(_a0 *types.MediaAnalysis, _a1 error) *MockManifestAnalyzer_AnalyzeHLS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManifestAnalyzer_AnalyzeHLS_Call) RunAndReturn(run func(string, types.EnvironmentConfig) (*types.MediaAnalysis, error)) *MockManifestAnalyzer_AnalyzeHLS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManifestAnalyzer creates a new instance of MockManifestAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifestAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifestAnalyzer {
	mock := &MockManifestAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
