// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/roddd/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockOutputWriter is an autogenerated mock type for the OutputWriter type
type MockOutputWriter struct {
	mock.Mock
}

type MockOutputWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputWriter) EXPECT() *MockOutputWriter_Expecter {
	return &MockOutputWriter_Expecter{mock: &_m.Mock}
}

// CopyToClipboard provides a mock function with given fields: text
func (_m *MockOutputWriter) CopyToClipboard(text string) error {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for CopyToClipboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutputWriter_CopyToClipboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyToClipboard'
type MockOutputWriter_CopyToClipboard_Call struct {
	*mock.Call
}

// CopyToClipboard is a helper method to define mock.On call
//   - text string
func (_e *MockOutputWriter_Expecter) CopyToClipboard(text interface{}) *MockOutputWriter_CopyToClipboard_Call {
	return &MockOutputWriter_CopyToClipboard_Call{Call: _e.mock.On("CopyToClipboard", text)}
}

func (_c *MockOutputWriter_CopyToClipboard_Call) Run(run func(text string)) *MockOutputWriter_CopyToClipboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOutputWriter_CopyToClipboard_Call) Return(_a0 error) *MockOutputWriter_CopyToClipboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutputWriter_CopyToClipboard_Call) RunAndReturn(run func(string) error) *MockOutputWriter_CopyToClipboard_Call {
	_c.Call.Return(run)
	return _c
}

// PrintSummary provides a mock function with given fields: keyMap, renditions
func (_m *MockOutputWriter) PrintSummary(keyMap map[string]types.KeyDetail, renditions []types.RenditionSummary) {
	_m.Called(keyMap, renditions)
}

// MockOutputWriter_PrintSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintSummary'
type MockOutputWriter_PrintSummary_Call struct {
	*mock.Call
}

// PrintSummary is a helper method to define mock.On call
//   - keyMap map[string]types.KeyDetail
//   - renditions []types.RenditionSummary
func (_e *MockOutputWriter_Expecter) PrintSummary(keyMap interface{}, renditions interface{}) *MockOutputWriter_PrintSummary_Call {
	return &MockOutputWriter_PrintSummary_Call{Call: _e.mock.On("PrintSummary", keyMap, renditions)}
}

func (_c *MockOutputWriter_PrintSummary_Call) Run(run func(keyMap map[string]types.KeyDetail, renditions []types.RenditionSummary)) *MockOutputWriter_PrintSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]types.KeyDetail), args[1].([]types.RenditionSummary))
	})
	return _c
}

func (_c *MockOutputWriter_PrintSummary_Call) Return() *MockOutputWriter_PrintSummary_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOutputWriter_PrintSummary_Call) RunAndReturn(run func(map[string]types.KeyDetail, []types.RenditionSummary)) *MockOutputWriter_PrintSummary_Call {
	_c.Run(run)
	return _c
}

// NewMockOutputWriter creates a new instance of MockOutputWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputWriter {
	mock := &MockOutputWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
