// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockS3Fetcher is an autogenerated mock type for the S3Fetcher type
type MockS3Fetcher struct {
	mock.Mock
}

type MockS3Fetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Fetcher) EXPECT() *MockS3Fetcher_Expecter {
	return &MockS3Fetcher_Expecter{mock: &_m.Mock}
}

// FetchContent provides a mock function with given fields: ctx, bucket, key
func (_m *MockS3Fetcher) FetchContent(ctx context.Context, bucket string, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for FetchContent")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, error)); ok {
		return rf(ctx, bucket, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3Fetcher_FetchContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchContent'
type MockS3Fetcher_FetchContent_Call struct {
	*mock.Call
}

// FetchContent is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockS3Fetcher_Expecter) FetchContent(ctx interface{}, bucket interface{}, key interface{}) *MockS3Fetcher_FetchContent_Call {
	return &MockS3Fetcher_FetchContent_Call{Call: _e.mock.On("FetchContent", ctx, bucket, key)}
}

func (_c *MockS3Fetcher_FetchContent_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockS3Fetcher_FetchContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockS3Fetcher_FetchContent_Call) Return(_a0 io.ReadCloser, _a1 error) *MockS3Fetcher_FetchContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3Fetcher_FetchContent_Call) RunAndReturn(run func(context.Context, string, string) (io.ReadCloser, error)) *MockS3Fetcher_FetchContent_Call {
	_c.Call.Return(run)
	return _c
}

// ListManifests provides a mock function with given fields: ctx, bucket, prefix, includeSubclips
func (_m *MockS3Fetcher) ListManifests(ctx context.Context, bucket string, prefix string, includeSubclips bool) ([]string, error) {
	ret := _m.Called(ctx, bucket, prefix, includeSubclips)

	if len(ret) == 0 {
		panic("no return value specified for ListManifests")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]string, error)); ok {
		return rf(ctx, bucket, prefix, includeSubclips)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []string); ok {
		r0 = rf(ctx, bucket, prefix, includeSubclips)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, bucket, prefix, includeSubclips)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3Fetcher_ListManifests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListManifests'
type MockS3Fetcher_ListManifests_Call struct {
	*mock.Call
}

// ListManifests is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix string
//   - includeSubclips bool
func (_e *MockS3Fetcher_Expecter) ListManifests(ctx interface{}, bucket interface{}, prefix interface{}, includeSubclips interface{}) *MockS3Fetcher_ListManifests_Call {
	return &MockS3Fetcher_ListManifests_Call{Call: _e.mock.On("ListManifests", ctx, bucket, prefix, includeSubclips)}
}

func (_c *MockS3Fetcher_ListManifests_Call) Run(run func(ctx context.Context, bucket string, prefix string, includeSubclips bool)) *MockS3Fetcher_ListManifests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockS3Fetcher_ListManifests_Call) Return(_a0 []string, _a1 error) *MockS3Fetcher_ListManifests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3Fetcher_ListManifests_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]string, error)) *MockS3Fetcher_ListManifests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockS3Fetcher creates a new instance of MockS3Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Fetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Fetcher {
	mock := &MockS3Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
