// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/roddd/whichkey/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockVaultClient is an autogenerated mock type for the VaultClient type
type MockVaultClient struct {
	mock.Mock
}

type MockVaultClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultClient) EXPECT() *MockVaultClient_Expecter {
	return &MockVaultClient_Expecter{mock: &_m.Mock}
}

// CheckKey provides a mock function with given fields: keyID, config
func (_m *MockVaultClient) CheckKey(keyID string, config types.EnvironmentConfig) (bool, error) {
	ret := _m.Called(keyID, config)

	if len(ret) == 0 {
		panic("no return value specified for CheckKey")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) (bool, error)); ok {
		return rf(keyID, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) bool); ok {
		r0 = rf(keyID, config)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) error); ok {
		r1 = rf(keyID, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultClient_CheckKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckKey'
type MockVaultClient_CheckKey_Call struct {
	*mock.Call
}

// CheckKey is a helper method to define mock.On call
//   - keyID string
//   - config types.EnvironmentConfig
func (_e *MockVaultClient_Expecter) CheckKey(keyID interface{}, config interface{}) *MockVaultClient_CheckKey_Call {
	return &MockVaultClient_CheckKey_Call{Call: _e.mock.On("CheckKey", keyID, config)}
}

func (_c *MockVaultClient_CheckKey_Call) Run(run func(keyID string, config types.EnvironmentConfig)) *MockVaultClient_CheckKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockVaultClient_CheckKey_Call) Return(_a0 bool, _a1 error) *MockVaultClient_CheckKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultClient_CheckKey_Call) RunAndReturn(run func(string, types.EnvironmentConfig) (bool, error)) *MockVaultClient_CheckKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyInfo provides a mock function with given fields: keyID, config
func (_m *MockVaultClient) GetKeyInfo(keyID string, config types.EnvironmentConfig) (map[string]interface{}, error) {
	ret := _m.Called(keyID, config)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) (map[string]interface{}, error)); ok {
		return rf(keyID, config)
	}
	if rf, ok := ret.Get(0).(func(string, types.EnvironmentConfig) map[string]interface{}); ok {
		r0 = rf(keyID, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.EnvironmentConfig) error); ok {
		r1 = rf(keyID, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultClient_GetKeyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyInfo'
type MockVaultClient_GetKeyInfo_Call struct {
	*mock.Call
}

// GetKeyInfo is a helper method to define mock.On call
//   - keyID string
//   - config types.EnvironmentConfig
func (_e *MockVaultClient_Expecter) GetKeyInfo(keyID interface{}, config interface{}) *MockVaultClient_GetKeyInfo_Call {
	return &MockVaultClient_GetKeyInfo_Call{Call: _e.mock.On("GetKeyInfo", keyID, config)}
}

func (_c *MockVaultClient_GetKeyInfo_Call) Run(run func(keyID string, config types.EnvironmentConfig)) *MockVaultClient_GetKeyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(types.EnvironmentConfig))
	})
	return _c
}

func (_c *MockVaultClient_GetKeyInfo_Call) Return(_a0 map[string]interface{}, _a1 error) *MockVaultClient_GetKeyInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultClient_GetKeyInfo_Call) RunAndReturn(run func(string, types.EnvironmentConfig) (map[string]interface{}, error)) *MockVaultClient_GetKeyInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultClient creates a new instance of MockVaultClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultClient {
	mock := &MockVaultClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
