version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - misspell
  disable:
    # Disable noctx - exec.Command without context is fine for CLI tools
    - noctx
    # Disable errcheck - too many false positives for CLI tools
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  goimports:
    local-prefixes:
      - github.com/roddd/whichkey

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - ifElseChain
      - elseif
      - assignOp

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam

    # Exclude some linters from main.go
    - path: cmd/whichkey/main\.go
      linters:
        - funlen

    # Exclude package naming for types package (it's intentionally named types)
    - path: internal/types/
      linters:
        - revive

  exclude:
    # Ignore revive var-naming for types package
    - "var-naming: avoid meaningless package names"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
