with-expecter: true
all: false
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}_mock.go"
packages:
  github.com/roddd/whichkey/internal/interfaces:
    config:
      dir: "internal/mocks"
      outpkg: mocks
    interfaces:
      HTTPClient:
      S3Fetcher:
      VaultClient:
      KMSClient:
      K8sClient:
      ConfigProvider:
      ManifestAnalyzer:
      OutputWriter:
